language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
  - composer test

matrix:
  allow_failures:
    - php: hhvm

after_success:
  - travis_retry php vendor/bin/coveralls -v
